### PR TITLE
use charm from github

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by rspavel — APPROVED** [review]
We may need to revert if this is abandoned in favor of the internal gerrit but I see no issue with this for now

**Comment by jbakosi** [comment]
I don't see their usual tags in the github repo. We have historically tracked and upgraded using tags. Do you propose to track the master now? If so, that's not a good idea, IMO.

**Comment by junghans** [comment]
Good point, submodules depend on hashed, but tags would be nice to have for updating.

@stwhite91: Could you mirror the tags, too?

**Comment by stwhite91** [comment]
The tags for recent releases and the 6.8.0 betas have been added now.

**Comment by junghans** [comment]
Thanks!

**Pull request merged**
