### PR TITLE
Add omega_h

### PR DESCRIPTION
**Pull request by junghans**
Also see https://github.com/quinoacomputing/cmake-modules/pull/21

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)

### CODE REVIEW

**Comment by jbakosi** [comment]
Thanks for adding this! See some comments below.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @junghans)

---

*[CMakeLists.txt, line 425 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPcfb1-y4W3ym-Ex5g:-LFPcfb1-y4W3ym-Ex5h:b63593r) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L425)):*
> ```CMake
> endif()
> 
> set(ENABLE_OMEGA_H ON CACHE BOOL "Enable BackwardCpp")
> ```

`Enable Omega_h`

Also, shall we set it to `off` by default? I think we should for now as this will be (for now) used for reading a mesh in inciter, which we already have a way to do.

---

*[CMakeLists.txt, line 1000 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPd0KFAlqk5u4yaLOo:-LFPd0KFAlqk5u4yaLOp:b3l2z39) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L1000)):*
> ```CMake
> #### Omega_h is a C++11 library that implements tetrahedron and triangle mesh adaptativity####
> # https://github.com/ibaned/omega_h
> # no support for CMAKE_BUILD_TYPE
> ```

Weird that it hard codes `-O3`.

@ibaned: Not a huge deal, but what is the reason for disallowing passing `CMAKE_BUILD_TYPE` to the _Omega_h_ build? Attempting to set it, I get
```
CMake Error at cmake/bob.cmake:153 (message):
  can't set CMAKE_BUILD_TYPE and use bob_*_cxx_flags
Call Stack (most recent call first):
  CMakeLists.txt:123 (bob_begin_cxx_flags)
```

---

*[CMakeLists.txt, line 1007 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPeHvm6C7vB2D2SSja:-LFPeHvm6C7vB2D2SSjb:bd38lir) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L1007)):*
> ```CMake
>     SOURCE_DIR ${PROJECT_SOURCE_DIR}/src/omega_h
>     CMAKE_ARGS -D CMAKE_CXX_COMPILER:PATH=${UNDERLYING_CXX_COMPILER}
>                -D CMAKE_CXX_FLAGS:STRING=${CXXFLAGS}
> ```

We definitely want MPI support:
```
-D Omega_h_USE_MPI:BOOL=on
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-:-LFPcR9_0bHbNXAMyfDX:bucg3gd)*

**Comment by jbakosi** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @junghans)

---

*[CMakeLists.txt, line 1007 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPeHvm6C7vB2D2SSja:-LFPho_k93qsoVeAzvSf:be76dzy) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L1007)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

We definitely want MPI support:
```
-D Omega_h_USE_MPI:BOOL=on
```
</blockquote></details>

Also:
```
-D CMAKE_CXX_COMPILER:PATH=${MPI_CXX_COMPILER}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Comment by jbakosi** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @junghans)

---

*[CMakeLists.txt, line 443 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPjPpp6aOuDpDvT7Rj:-LFPjPpp6aOuDpDvT7Rk:b-mzsij) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L443)):*
> ```CMake
> ${cartesian_product} ${rngsse2} ${testu01} ${h5part} ${hdf5} ${netcdf}
> ${boost} ${pstreams} ${hypre} ${pugixml} ${lapack} ${aec} ${numdiff} ${root}
> ${backwardcpp} ${highwayhash})
> ```

Oh, and don't forget to add `${omega_h}` to this list.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Comment by ibaned** [comment]
@jbakosi @junghans Thanks for this PR! With respect to `CMAKE_BUILD_TYPE`, I don't like what Kitware did with `Release` (no symbols, even though they don't slow code down) or `Debug` (no optimization, code is very slow), I think `RelWithDebInfo` is the only reasonable one, and compiler-specific warning flags are also added (also CUDA/OpenMP, the list goes on). Anyways, Omega_h works well with control of its own flags. However, I did recently add an xSDK compatibility layer, you can define
```
-DUSE_XSDK_DEFAULTS:BOOL=ON
```
To enable this simplified mode, in which I think `CMAKE_BUILD_TYPE` will take effect.

**Comment by jbakosi** [comment]
Thanks @ibaned . Not really a big deal, I was just curious. We will most likely have some questions when we are putting in an osh reader soon based on [#211](https://github.com/quinoacomputing/quinoa/issues/211).

**Comment by junghans** [comment]
Review status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @jbakosi)

---

*[CMakeLists.txt, line 425 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPcfb1-y4W3ym-Ex5g:-LFSnE4e2OjDhmtsr7Dm:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L425)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`Enable Omega_h`

Also, shall we set it to `off` by default? I think we should for now as this will be (for now) used for reading a mesh in inciter, which we already have a way to do.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 443 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPjPpp6aOuDpDvT7Rj:-LFSnEaA75B6bdEUVsVl:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L443)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Oh, and don't forget to add `${omega_h}` to this list.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 1000 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPd0KFAlqk5u4yaLOo:-LFSnF11CTIb0bkAo0OY:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L1000)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Weird that it hard codes `-O3`.

@ibaned: Not a huge deal, but what is the reason for disallowing passing `CMAKE_BUILD_TYPE` to the _Omega_h_ build? Attempting to set it, I get
```
CMake Error at cmake/bob.cmake:153 (message):
  can't set CMAKE_BUILD_TYPE and use bob_*_cxx_flags
Call Stack (most recent call first):
  CMakeLists.txt:123 (bob_begin_cxx_flags)
```
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 1007 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPeHvm6C7vB2D2SSja:-LFSnGsU8YNhPZtuXeZO:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L1007)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Also:
```
-D CMAKE_CXX_COMPILER:PATH=${MPI_CXX_COMPILER}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Comment by jbakosi** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jbakosi)

---

*[CMakeLists.txt, line 425 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-LFPcfb1-y4W3ym-Ex5g:-LFSw1BPAkpPkxBhPZia:b8n5j92) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/6718ad34d825849c8064c9ed980dab0d96769394/CMakeLists.txt#L425)):*
<details><summary><i>Previously, junghans (Christoph Junghans) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It still `on` by default. We should have it `off`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Comment by jbakosi** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @junghans)

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Comment by jbakosi** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed, all discussions resolved (waiting on @jbakosi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-:-LFT5LRtAvnPmbmi3O3z:bnfp4nl)*

**Comment by jbakosi** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27)*

**Review by jbakosi — APPROVED** [review]
LGTM. Please merge and don't forget to sign.

**Comment by jbakosi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/27#-:-LG2rK4L2Wuc3fs6jHye:bnfp4nl)*

**Pull request merged**
