### PR TITLE
Remove ROOT

### PR DESCRIPTION
**Pull request by junghans**
Also see the `all` branch: https://github.com/quinoacomputing/quinoa-tpl/compare/remove_root...all

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25)

### CODE REVIEW

**Comment by jbakosi** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 391 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25#-LEt5pO68UYjMkhNuMJh:-LEt5pO68UYjMkhNuMJi:b-esvb93) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/c872a1bdd575323f991a19a0975ac5efadb46071/CMakeLists.txt#L391)):*
> ```CMake
>     set(root "")
>   elseif(NOT EXISTS ${PROJECT_SOURCE_DIR}/src/root/CMakeLists.txt)
>     message(WARNING "ROOT enabled, not found on system and not checkout as git submodule (try switching to 'all branch of the tpl repository")
> ```

Do I understand the intent that this is the following?
```
ROOT enabled but not found on system and not found as a git submodule. If you want ROOT, try switching to branch 'all' of the TPL repository.
```
If so, feel like the above comment is more clear.

So branch `remove_root` will become `master` and `all` will stay around?

There are at least two ways of working with the TPL repo: standalone or as part of a recursive clone of quinoa. It would be good to give exact instructions in the above message on how to checkout/clone ROOT using in standalone or with submodules. Do you agree?

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25)*

**Comment by jbakosi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25)*

**Comment by junghans** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @junghans)

---

*[CMakeLists.txt, line 391 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25#-LEt5pO68UYjMkhNuMJh:-LEtb5gUDhBN1CKs9nRB:bduthle) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/c872a1bdd575323f991a19a0975ac5efadb46071/CMakeLists.txt#L391)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Do I understand the intent that this is the following?
```
ROOT enabled but not found on system and not found as a git submodule. If you want ROOT, try switching to branch 'all' of the TPL repository.
```
If so, feel like the above comment is more clear.

So branch `remove_root` will become `master` and `all` will stay around?

There are at least two ways of working with the TPL repo: standalone or as part of a recursive clone of quinoa. It would be good to give exact instructions in the above message on how to checkout/clone ROOT using in standalone or with submodules. Do you agree?
</blockquote></details>

Yes, `all` will stick around and `remove_root` will be merged into `master`.

I will update the message, but turning it into a git tutorial seems a bit too much. By default users will have the master branch, so a `git checkout all` should to it all.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25)*

**Comment by jbakosi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 391 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25#-LEt5pO68UYjMkhNuMJh:-LEtdN0Q55LT3mbkJTqy:bwqhnli) ([raw file](https://github.com/quinoacomputing/quinoa-tpl/blob/c872a1bdd575323f991a19a0975ac5efadb46071/CMakeLists.txt#L391)):*
<details><summary><i>Previously, junghans (Christoph Junghans) wrote…</i></summary><blockquote>

Yes, `all` will stick around and `remove_root` will be merged into `master`.

I will update the message, but turning it into a git tutorial seems a bit too much. By default users will have the master branch, so a `git checkout all` should to it all.
</blockquote></details>

Yeah, no I don't want a git tutorial either. Let's just suggest a git command in the message for the use case of a recursive clone.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa-tpl/25)*

**Pull request merged**
